Step 1
minnce/shxiv pull request #2
Opened 2023-09-14 19:08 UTC by minnce

wtf

2023-09-14 19:26 UTC, echavemann requested changes

2023-09-14 19:26 UTC, echavemann commented on src/pricingutil.cpp
> +PricingUtil::PricingUtil() {}
initialize val jeez

2023-09-14 23:05 UTC, minnce commented on src/pricingutil.cpp
> +PricingUtil::PricingUtil() {}
dome

2023-09-17 17:46 UTC, echavemann reviewed
lgtm

2023-09-17 17:46 UTC, echavemann approved these changes

2023-09-18 04:56 UTC, merged